[2022-04-29 15:30:31,963] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cdn_daily.import_pre.check_status_of_pre manual__2022-04-29T15:30:28.273551+00:00 [queued]>
[2022-04-29 15:30:32,003] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cdn_daily.import_pre.check_status_of_pre manual__2022-04-29T15:30:28.273551+00:00 [queued]>
[2022-04-29 15:30:32,005] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 15:30:32,009] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-04-29 15:30:32,010] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 15:30:32,042] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): import_pre.check_status_of_pre> on 2022-04-29 15:30:28.273551+00:00
[2022-04-29 15:30:32,052] {standard_task_runner.py:52} INFO - Started process 3667 to run task
[2022-04-29 15:30:32,063] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cdn_daily', 'import_pre.check_status_of_pre', 'manual__2022-04-29T15:30:28.273551+00:00', '--job-id', '1681', '--raw', '--subdir', 'DAGS_FOLDER/cdn_daily.py', '--cfg-path', '/tmp/tmpn6q8tzu2', '--error-file', '/tmp/tmpxjhvb37f']
[2022-04-29 15:30:32,068] {standard_task_runner.py:77} INFO - Job 1681: Subtask import_pre.check_status_of_pre
[2022-04-29 15:30:32,203] {logging_mixin.py:109} INFO - Running <TaskInstance: cdn_daily.import_pre.check_status_of_pre manual__2022-04-29T15:30:28.273551+00:00 [running]> on host d5ad096ffea5
[2022-04-29 15:30:32,313] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cdn_daily
AIRFLOW_CTX_TASK_ID=import_pre.check_status_of_pre
AIRFLOW_CTX_EXECUTION_DATE=2022-04-29T15:30:28.273551+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-29T15:30:28.273551+00:00
[2022-04-29 15:30:32,317] {logging_mixin.py:109} INFO - run_pre
[2022-04-29 15:30:32,333] {logging_mixin.py:109} INFO - None
[2022-04-29 15:30:32,349] {logging_mixin.py:109} INFO - pre.alm
[2022-04-29 15:30:32,372] {logging_mixin.py:109} INFO - None
[2022-04-29 15:30:32,374] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/commons/cdn_daily_functions.py", line 18, in status_check
    time.sleep(int(pause))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2022-04-29 15:30:32,410] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=cdn_daily, task_id=import_pre.check_status_of_pre, execution_date=20220429T153028, start_date=20220429T153031, end_date=20220429T153032
[2022-04-29 15:30:32,456] {standard_task_runner.py:92} ERROR - Failed to execute job 1681 for task import_pre.check_status_of_pre
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/commons/cdn_daily_functions.py", line 18, in status_check
    time.sleep(int(pause))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2022-04-29 15:30:32,490] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-29 15:30:32,546] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
