[2022-04-28 13:11:38,781] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cdn_daily.import_bsre.check_presence_of_bsre2 scheduled__2022-04-27T12:55:05.495602+00:00 [queued]>
[2022-04-28 13:11:38,812] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cdn_daily.import_bsre.check_presence_of_bsre2 scheduled__2022-04-27T12:55:05.495602+00:00 [queued]>
[2022-04-28 13:11:38,814] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 13:11:38,816] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-04-28 13:11:38,817] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 13:11:38,853] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): import_bsre.check_presence_of_bsre2> on 2022-04-27 12:55:05.495602+00:00
[2022-04-28 13:11:38,867] {standard_task_runner.py:52} INFO - Started process 1231 to run task
[2022-04-28 13:11:38,894] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cdn_daily', 'import_bsre.check_presence_of_bsre2', 'scheduled__2022-04-27T12:55:05.495602+00:00', '--job-id', '1406', '--raw', '--subdir', 'DAGS_FOLDER/cdn_daily.py', '--cfg-path', '/tmp/tmpgzqmi819', '--error-file', '/tmp/tmp9zrlor83']
[2022-04-28 13:11:38,898] {standard_task_runner.py:77} INFO - Job 1406: Subtask import_bsre.check_presence_of_bsre2
[2022-04-28 13:11:39,141] {logging_mixin.py:109} INFO - Running <TaskInstance: cdn_daily.import_bsre.check_presence_of_bsre2 scheduled__2022-04-27T12:55:05.495602+00:00 [running]> on host d5ad096ffea5
[2022-04-28 13:11:39,450] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cdn_daily
AIRFLOW_CTX_TASK_ID=import_bsre.check_presence_of_bsre2
AIRFLOW_CTX_EXECUTION_DATE=2022-04-27T12:55:05.495602+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-27T12:55:05.495602+00:00
[2022-04-28 13:11:39,453] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/commons/cdn_daily_functions.py", line 41, in files_check
    task_instance.xcom_push(key='filename',value=filename),
NameError: name 'task_instance' is not defined
[2022-04-28 13:11:39,501] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=cdn_daily, task_id=import_bsre.check_presence_of_bsre2, execution_date=20220427T125505, start_date=20220428T131138, end_date=20220428T131139
[2022-04-28 13:11:39,539] {standard_task_runner.py:92} ERROR - Failed to execute job 1406 for task import_bsre.check_presence_of_bsre2
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/commons/cdn_daily_functions.py", line 41, in files_check
    task_instance.xcom_push(key='filename',value=filename),
NameError: name 'task_instance' is not defined
[2022-04-28 13:11:39,589] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-28 13:11:39,754] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
