[2022-04-28 15:40:08,659] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cdn_daily.import_cat.check_status_of_cat.alm manual__2022-04-28T15:35:02.887842+00:00 [queued]>
[2022-04-28 15:40:08,679] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cdn_daily.import_cat.check_status_of_cat.alm manual__2022-04-28T15:35:02.887842+00:00 [queued]>
[2022-04-28 15:40:08,681] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 15:40:08,683] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-04-28 15:40:08,684] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 15:40:08,704] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): import_cat.check_status_of_cat.alm> on 2022-04-28 15:35:02.887842+00:00
[2022-04-28 15:40:08,711] {standard_task_runner.py:52} INFO - Started process 1900 to run task
[2022-04-28 15:40:08,717] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cdn_daily', 'import_cat.check_status_of_cat.alm', 'manual__2022-04-28T15:35:02.887842+00:00', '--job-id', '1461', '--raw', '--subdir', 'DAGS_FOLDER/cdn_daily.py', '--cfg-path', '/tmp/tmphigrprep', '--error-file', '/tmp/tmp_qwxtwhb']
[2022-04-28 15:40:08,718] {standard_task_runner.py:77} INFO - Job 1461: Subtask import_cat.check_status_of_cat.alm
[2022-04-28 15:40:08,803] {logging_mixin.py:109} INFO - Running <TaskInstance: cdn_daily.import_cat.check_status_of_cat.alm manual__2022-04-28T15:35:02.887842+00:00 [running]> on host d5ad096ffea5
[2022-04-28 15:40:08,870] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cdn_daily
AIRFLOW_CTX_TASK_ID=import_cat.check_status_of_cat.alm
AIRFLOW_CTX_EXECUTION_DATE=2022-04-28T15:35:02.887842+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-28T15:35:02.887842+00:00
[2022-04-28 15:40:08,882] {logging_mixin.py:109} INFO - None
[2022-04-28 15:40:08,893] {logging_mixin.py:109} INFO - None
[2022-04-28 15:40:08,894] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/commons/cdn_daily_functions.py", line 15, in status_check
    time.sleep(int(pause))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2022-04-28 15:40:08,914] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=cdn_daily, task_id=import_cat.check_status_of_cat.alm, execution_date=20220428T153502, start_date=20220428T154008, end_date=20220428T154008
[2022-04-28 15:40:08,934] {standard_task_runner.py:92} ERROR - Failed to execute job 1461 for task import_cat.check_status_of_cat.alm
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/commons/cdn_daily_functions.py", line 15, in status_check
    time.sleep(int(pause))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2022-04-28 15:40:08,975] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-28 15:40:09,040] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
