[2022-03-29 14:17:13,550] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.xsxsxqc.xsxsxqc_get_data scheduled__2022-03-28T12:54:27.698780+00:00 [queued]>
[2022-03-29 14:17:13,598] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.xsxsxqc.xsxsxqc_get_data scheduled__2022-03-28T12:54:27.698780+00:00 [queued]>
[2022-03-29 14:17:13,600] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-29 14:17:13,601] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-29 14:17:13,603] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-29 14:17:13,642] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): xsxsxqc.xsxsxqc_get_data> on 2022-03-28 12:54:27.698780+00:00
[2022-03-29 14:17:13,658] {standard_task_runner.py:52} INFO - Started process 896 to run task
[2022-03-29 14:17:13,667] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'xsxsxqc.xsxsxqc_get_data', 'scheduled__2022-03-28T12:54:27.698780+00:00', '--job-id', '1050', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpap72li91', '--error-file', '/tmp/tmp0l0pmen7']
[2022-03-29 14:17:13,672] {standard_task_runner.py:77} INFO - Job 1050: Subtask xsxsxqc.xsxsxqc_get_data
[2022-03-29 14:17:13,910] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.xsxsxqc.xsxsxqc_get_data scheduled__2022-03-28T12:54:27.698780+00:00 [running]> on host ff48034dfdbf
[2022-03-29 14:17:14,183] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=xsxsxqc.xsxsxqc_get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-03-28T12:54:27.698780+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-28T12:54:27.698780+00:00
[2022-03-29 16:17:46,788] {local_task_job.py:212} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2022-03-29 16:17:46,799] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 896. PIDs of all processes in the group: [896]
[2022-03-29 16:17:46,804] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 896
[2022-03-29 16:17:46,807] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-03-29 16:17:47,076] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 35, in task_pause
    time.sleep(60)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-03-29 16:17:47,107] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=tutorial, task_id=xsxsxqc.xsxsxqc_get_data, execution_date=20220328T125427, start_date=20220329T141713, end_date=20220329T161747
[2022-03-29 16:17:47,148] {standard_task_runner.py:92} ERROR - Failed to execute job 1050 for task xsxsxqc.xsxsxqc_get_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 35, in task_pause
    time.sleep(60)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-03-29 16:17:47,195] {process_utils.py:70} INFO - Process psutil.Process(pid=896, status='terminated', exitcode=1, started='14:17:13') (896) terminated with exit code 1
