[2021-02-24 20:56:19,095] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: example_dag_decorator.send_email 2021-02-24T20:56:15.251518+00:00 [queued]>
[2021-02-24 20:56:19,106] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: example_dag_decorator.send_email 2021-02-24T20:56:15.251518+00:00 [queued]>
[2021-02-24 20:56:19,107] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-24 20:56:19,107] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-24 20:56:19,108] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-24 20:56:19,126] {taskinstance.py:1038} INFO - Executing <Task(EmailOperator): send_email> on 2021-02-24T20:56:15.251518+00:00
[2021-02-24 20:56:19,131] {standard_task_runner.py:51} INFO - Started process 41 to run task
[2021-02-24 20:56:19,136] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'example_dag_decorator', 'send_email', '2021-02-24T20:56:15.251518+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py', '--cfg-path', '/tmp/tmp8q_p3_wq']
[2021-02-24 20:56:19,137] {standard_task_runner.py:76} INFO - Job 12: Subtask send_email
[2021-02-24 20:56:19,190] {logging_mixin.py:103} INFO - Running <TaskInstance: example_dag_decorator.send_email 2021-02-24T20:56:15.251518+00:00 [running]> on host 4fa4dc1e93c4
[2021-02-24 20:56:19,270] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_dag_decorator
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2021-02-24T20:56:15.251518+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-24T20:56:15.251518+00:00
[2021-02-24 20:56:19,274] {configuration.py:344} WARNING - section/key [smtp/smtp_user] not found in config
[2021-02-24 20:56:19,275] {email.py:184} INFO - Email alerting: attempt 1
[2021-02-24 20:56:19,277] {taskinstance.py:1396} ERROR - [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 52, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 97, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 186, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 220, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 308, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2021-02-24 20:56:19,285] {taskinstance.py:1433} INFO - Marking task as FAILED. dag_id=example_dag_decorator, task_id=send_email, execution_date=20210224T205615, start_date=20210224T205619, end_date=20210224T205619
[2021-02-24 20:56:19,349] {local_task_job.py:118} INFO - Task exited with return code 1
