[2022-04-29 15:23:23,207] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cdn_daily.import_bsre.check_status_of_bsre manual__2022-04-29T15:23:19.038785+00:00 [queued]>
[2022-04-29 15:23:23,226] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cdn_daily.import_bsre.check_status_of_bsre manual__2022-04-29T15:23:19.038785+00:00 [queued]>
[2022-04-29 15:23:23,228] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 15:23:23,229] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-04-29 15:23:23,230] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 15:23:23,250] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): import_bsre.check_status_of_bsre> on 2022-04-29 15:23:19.038785+00:00
[2022-04-29 15:23:23,257] {standard_task_runner.py:52} INFO - Started process 3273 to run task
[2022-04-29 15:23:23,263] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cdn_daily', 'import_bsre.check_status_of_bsre', 'manual__2022-04-29T15:23:19.038785+00:00', '--job-id', '1634', '--raw', '--subdir', 'DAGS_FOLDER/cdn_daily.py', '--cfg-path', '/tmp/tmpowufmuhk', '--error-file', '/tmp/tmpqxyvj7ln']
[2022-04-29 15:23:23,269] {standard_task_runner.py:77} INFO - Job 1634: Subtask import_bsre.check_status_of_bsre
[2022-04-29 15:23:23,361] {logging_mixin.py:109} INFO - Running <TaskInstance: cdn_daily.import_bsre.check_status_of_bsre manual__2022-04-29T15:23:19.038785+00:00 [running]> on host d5ad096ffea5
[2022-04-29 15:23:23,446] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cdn_daily
AIRFLOW_CTX_TASK_ID=import_bsre.check_status_of_bsre
AIRFLOW_CTX_EXECUTION_DATE=2022-04-29T15:23:19.038785+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-29T15:23:19.038785+00:00
[2022-04-29 15:23:23,448] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/commons/cdn_daily_functions.py", line 11, in status_check
    task_id="run_"+source.key()
AttributeError: 'str' object has no attribute 'key'
[2022-04-29 15:23:23,474] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=cdn_daily, task_id=import_bsre.check_status_of_bsre, execution_date=20220429T152319, start_date=20220429T152323, end_date=20220429T152323
[2022-04-29 15:23:23,494] {standard_task_runner.py:92} ERROR - Failed to execute job 1634 for task import_bsre.check_status_of_bsre
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/commons/cdn_daily_functions.py", line 11, in status_check
    task_id="run_"+source.key()
AttributeError: 'str' object has no attribute 'key'
[2022-04-29 15:23:23,521] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-29 15:23:23,581] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
