[2022-03-29 14:17:13,366] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-03-28T12:54:27.698780+00:00 [queued]>
[2022-03-29 14:17:13,402] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-03-28T12:54:27.698780+00:00 [queued]>
[2022-03-29 14:17:13,404] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-29 14:17:13,406] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-29 14:17:13,407] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-29 14:17:13,436] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cat.cat_get_data> on 2022-03-28 12:54:27.698780+00:00
[2022-03-29 14:17:13,445] {standard_task_runner.py:52} INFO - Started process 894 to run task
[2022-03-29 14:17:13,453] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'cat.cat_get_data', 'scheduled__2022-03-28T12:54:27.698780+00:00', '--job-id', '1048', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp42z2jeg4', '--error-file', '/tmp/tmp8s7zp0uo']
[2022-03-29 14:17:13,455] {standard_task_runner.py:77} INFO - Job 1048: Subtask cat.cat_get_data
[2022-03-29 14:17:13,657] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-03-28T12:54:27.698780+00:00 [running]> on host ff48034dfdbf
[2022-03-29 14:17:13,864] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=cat.cat_get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-03-28T12:54:27.698780+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-28T12:54:27.698780+00:00
[2022-03-29 16:17:46,632] {local_task_job.py:212} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2022-03-29 16:17:46,639] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 894. PIDs of all processes in the group: [894]
[2022-03-29 16:17:46,642] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 894
[2022-03-29 16:17:46,644] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-03-29 16:17:46,678] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 35, in task_pause
    time.sleep(60)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-03-29 16:17:46,718] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=tutorial, task_id=cat.cat_get_data, execution_date=20220328T125427, start_date=20220329T141713, end_date=20220329T161746
[2022-03-29 16:17:46,748] {standard_task_runner.py:92} ERROR - Failed to execute job 1048 for task cat.cat_get_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 35, in task_pause
    time.sleep(60)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-03-29 16:17:46,792] {process_utils.py:70} INFO - Process psutil.Process(pid=894, status='terminated', exitcode=1, started='14:17:13') (894) terminated with exit code 1
